version: '3.8'

services:
  finders_backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8181
    volumes:
      - .:/code
    ports:
      - "8181:8181"
    env_file:
      - .env
    depends_on:
      - finders_db
    restart: always

  finders_db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: always

volumes:
  pgdata:
